#!/usr/bin/env python3
# Generates the canonical .resw catalogues for Computer Archaeologist.
# One source of truth for the embedded Core catalogue and the Windows App SDK PRI pipeline.
import os, sys

EN = {}
ZH = {}

def k(key, en, zh):
    assert key not in EN, f"duplicate key {key}"
    EN[key] = en
    ZH[key] = zh

# ---------------------------------------------------------------- application shell
k("App_DisplayName", "Computer Archaeologist", "计算机考古学家")
k("App_Tagline", "Rediscover the forgotten corners of your computer.", "重新发现电脑里被遗忘的角落。")
k("Nav_Home", "Home", "主页")
k("Nav_Archaeology", "Archaeology", "考古")
k("Nav_Discoveries", "Discoveries", "发现")
k("Nav_Reports", "Reports", "报告")
k("Nav_Settings", "Settings", "设置")
k("Nav_History", "Previous runs", "历史记录")

# ---------------------------------------------------------------- common
k("Common_OK", "OK", "确定")
k("Common_Cancel", "Cancel", "取消")
k("Common_Close", "Close", "关闭")
k("Common_Retry", "Retry", "重试")
k("Common_Copy", "Copy path", "复制路径")
k("Common_Copied", "Path copied to the clipboard.", "路径已复制到剪贴板。")
k("Common_Save", "Save", "保存")
k("Common_Saved", "Settings saved.", "设置已保存。")
k("Common_Remove", "Remove", "移除")
k("Common_Add", "Add", "添加")
k("Common_Refresh", "Refresh", "刷新")
k("Common_Open", "Open", "打开")
k("Common_Browse", "Browse…", "浏览…")
k("Common_Loading", "Loading…", "正在加载…")
k("Common_Unknown", "Unknown", "未知")
k("Common_None", "None", "无")
k("Common_Details", "Details", "详情")
k("Common_Close2", "Dismiss", "关闭")

# ---------------------------------------------------------------- home
k("Home_HeroTitle", "Computer Archaeologist", "计算机考古学家")
k("Home_HeroSubtitle", "Rediscover the forgotten corners of your computer.", "重新发现电脑里被遗忘的角落。")
k("Home_HeroBody",
  "Search your own machine for the files that carry history: abandoned projects, old documents, strange one-offs and things you forgot you ever made. Everything stays local unless you allow AI analysis.",
  "在自己的电脑里寻找有历史痕迹的文件：被放弃的项目、老文档、奇怪的一次性文件，以及你早已忘记自己做过的东西。除非你允许 AI 分析，否则一切都在本地完成。")
k("Home_Start", "Start Archaeology", "开始考古")
k("Home_Ready", "Ready to explore.", "准备好了，随时可以开始。")
k("Home_LastRun", "Last archaeology run", "上一次考古")
k("Home_Never", "Never", "从未")
k("Home_Stat_Scanned", "Files scanned", "已扫描文件")
k("Home_Stat_Candidates", "Candidates scored", "候选文件")
k("Home_Stat_Discoveries", "Discoveries", "有趣发现")
k("Home_Stat_Ai", "AI analysed", "AI 分析")
k("Home_Stat_Duration", "Duration", "耗时")
k("Home_LastReport", "Latest report", "最近一次报告")
k("Home_OpenLastReport", "Open report", "查看报告")
k("Home_NoReport", "No report yet.", "还没有报告。")
k("Home_NoReportHint", "Run an archaeology scan and a full report will appear here.", "运行一次考古扫描后，完整报告会出现在这里。")
k("Home_EverythingMissing", "Everything is not available. Archaeology will be slower or unavailable.", "Everything 不可用，考古速度会变慢或无法运行。")
k("Home_ApiMissing", "Configure an OpenAI-compatible API to enable AI archaeology.", "配置一个 OpenAI 兼容 API 即可启用 AI 考古。")
k("Home_CardPlaceholderTitle", "Old Project", "旧项目")
k("Home_CardPlaceholderCaption", "Rediscover the forgotten corners of your computer.", "重新发现电脑里被遗忘的角落。")
k("Home_CardKind", "Forgotten Project", "被遗忘的项目")
k("Home_FoundCard_Year", "2017", "2017")
k("Home_FoundCard_Score", "Interestingness", "有趣值")
k("Home_RecentSessions", "Previous runs", "历史记录")
k("Home_HistoryEmpty", "No previous runs recorded.", "还没有历史记录。")

# ---------------------------------------------------------------- scope dialog
k("Scope_Title", "Choose what to explore", "选择考古范围")
k("Scope_Subtitle", "Everything is used to search. Pick how wide the net should be cast.", "使用 Everything 进行检索，选择搜索范围。")
k("Scope_Entire", "Entire computer", "整台电脑")
k("Scope_Entire_Desc", "All indexed fixed drives.", "所有已索引的本地磁盘。")
k("Scope_Drive", "Drive {0}", "磁盘 {0}")
k("Scope_Folders", "Selected folders", "指定文件夹")
k("Scope_ChooseFolder", "Choose a folder…", "选择文件夹…")
k("Scope_SelectedNone", "No folder selected yet; the entire computer will be searched.", "尚未选择文件夹，将搜索整台电脑。")
k("Scope_Start", "Begin archaeology", "开始考古")

# ---------------------------------------------------------------- archaeology page
k("Arch_Title", "Archaeology", "考古")
k("Arch_Subtitle", "Seven stages, from the file index to a written report.", "从文件索引到考古报告，共七个阶段。")
k("Arch_Start", "Start", "开始")
k("Arch_Cancel", "Cancel", "取消")
k("Arch_Cancelling", "Cancelling safely…", "正在安全取消…")
k("Arch_Idle", "No archaeology run in progress.", "当前没有进行中的考古。")
k("Arch_StageList", "Stages", "阶段")
k("Arch_Current", "Currently examining", "当前处理")
k("Arch_Scanned", "Files discovered", "已发现文件")
k("Arch_OfTotal", "{0} / {1}", "{0} / {1}")
k("Arch_Candidates", "Candidates", "候选数量")
k("Arch_AiAnalyzed", "AI analysed", "AI 已分析")
k("Arch_Overall", "Overall progress", "总进度")
k("Arch_LogSummary", "Log summary", "日志摘要")
k("Arch_Complete", "Archaeology complete.", "考古完成。")
k("Arch_Cancelled", "Run cancelled. Partial results were kept.", "已取消，已完成的部分结果被保留。")
k("Arch_Failed", "The run could not be completed.", "本次运行未能完成。")
k("Arch_NoEverythingTitle", "Everything is required for high-speed archaeology.", "高速考古需要 Everything。")
k("Arch_NoEverythingMessage",
  "Computer Archaeologist uses the Everything index instead of walking your drives. Install Everything and start it, then check again. Alternatively you can allow the slower built-in enumerator in Settings.",
  "计算机考古学家使用 Everything 索引，而不是遍历整个磁盘。请安装并启动 Everything，然后重新检测。你也可以在设置中允许使用较慢的内置枚举器。")
k("Arch_CheckAgain", "Check again", "重新检测")
k("Arch_GetSdk", "Download official SDK", "下载官方 SDK")
k("Arch_GettingSdk", "Downloading the official Everything SDK…", "正在下载 Everything 官方 SDK…")
k("Arch_SdkInstalled", "The official Everything SDK was installed.", "Everything 官方 SDK 已安装。")
k("Arch_SdkFailed", "The Everything SDK could not be downloaded.", "Everything SDK 下载失败。")
k("Arch_OpenEverythingSite", "Get Everything", "获取 Everything")
k("Arch_PrivacyNotice",
  "Local-first: file discovery and scoring happen entirely on this machine. Only the selected candidates are ever sent to the configured AI endpoint.",
  "本地优先：文件发现与评分完全在本机完成。只有被选中的候选文件才会发送到你配置的 AI 接口。")
k("Arch_Stage_CheckingEverything", "Checking Everything", "检查 Everything")
k("Arch_Stage_Discovering", "Searching files", "搜索文件")
k("Arch_Stage_Metadata", "Collecting file metadata", "收集文件元数据")
k("Arch_Stage_LocalScore", "Computing local interestingness", "计算本地有趣值")
k("Arch_Stage_Context", "Reading folder context", "读取文件夹上下文")
k("Arch_Stage_Ai", "AI analysis of candidates", "AI 分析候选文件")
k("Arch_Stage_FinalScore", "Combining scores", "综合评分")
k("Arch_Stage_Report", "Generating report", "生成报告")
k("Arch_Stage_Completed", "Completed", "已完成")
k("Arch_Stage_Cancelled", "Cancelled", "已取消")
k("Arch_Stage_Failed", "Failed", "失败")
k("Arch_Stage_Idle", "Idle", "空闲")

# ---------------------------------------------------------------- discoveries
k("Disc_Title", "Discoveries", "发现")
k("Disc_Subtitle", "We found {0} artifacts worth looking at.", "共找到 {0} 个值得一看的文件。")
k("Disc_Empty", "No archaeological discoveries yet.", "还没有发现值得考古的文件。")
k("Disc_EmptyHint", "Start an archaeology run to look for forgotten projects, old documents and strange files.", "开始一次考古，寻找被遗忘的项目、老文档和奇怪的文件。")
k("Disc_Sort", "Sort by", "排序")
k("Disc_Sort_MostInteresting", "Most Interesting", "最有趣")
k("Disc_Sort_Oldest", "Oldest", "最古老")
k("Disc_Sort_Strangest", "Strangest", "最奇怪")
k("Disc_Sort_MostPersonal", "Most Personal", "最个人")
k("Disc_Sort_MostTechnical", "Most Technical", "最技术")
k("Disc_Sort_Largest", "Largest", "最大")
k("Disc_Filter", "Category", "类别")
k("Disc_AllCategories", "All categories", "全部类别")
k("Disc_OpenFile", "Open file", "打开文件")
k("Disc_OpenFolder", "Open folder", "打开所在文件夹")
k("Disc_Details", "Details", "详情")
k("Disc_Rank", "#{0}", "第 {0} 位")
k("Disc_ScoreLabel", "Interestingness", "有趣值")

# ---------------------------------------------------------------- discovery detail
k("Detail_Why", "Why we found it", "为什么它有趣")
k("Detail_Evidence", "Evidence", "证据")
k("Detail_AiConfidence", "AI confidence", "AI 置信度")
k("Detail_ScoreBreakdown", "Score breakdown", "评分明细")
k("Detail_RelatedFiles", "Related files", "相关文件")
k("Detail_NoRelated", "No related files were observed in this folder.", "该文件夹中未发现相关文件。")
k("Detail_Timeline", "Timeline", "时间线")
k("Detail_Facts", "Facts", "事实")
k("Detail_AiInterpretation", "AI interpretation", "AI 推断")
k("Detail_LocalFacts", "Measured locally", "本地测量")
k("Detail_NoAi", "AI analysis was unavailable for this artifact.", "该文件没有可用的 AI 分析。")
k("Detail_Preview", "Preview", "预览")
k("Detail_PreviewUnavailable", "No preview is available for this file type.", "该文件类型暂不支持预览。")
k("Detail_ContentNotSent", "File content was not read or sent (metadata-only mode).", "未读取或发送文件内容（仅元数据模式）。")
k("Detail_ContentSent", "A bounded excerpt ({0}) was included in the AI request.", "已向 AI 请求中附带有限的内容摘要（{0}）。")
k("Detail_ExecutableTitle", "This file is executable", "该文件是可执行文件")
k("Detail_ExecutableMessage", "This file is executable. Are you sure you want to open it?", "这是一个可执行文件，确定要打开它吗？")
k("Detail_OpenAnyway", "Open anyway", "仍然打开")
k("Detail_FileInfo", "File information", "文件信息")
k("Detail_LocalReasons", "Local reasons", "本地原因")
k("Detail_AiReasons", "AI reasons", "AI 原因")
k("Detail_Weight", "Weight", "权重")
k("Detail_Value", "Value", "数值")
k("Detail_Contribution", "Contribution", "贡献")
k("Detail_Back", "Back", "返回")
k("Detail_NarrativeNote", "Report note", "报告注记")

# ---------------------------------------------------------------- feature names
k("Feature_Age", "Age", "年龄")
k("Feature_Rarity", "Rarity", "稀有度")
k("Feature_PathContext", "Folder context", "路径语境")
k("Feature_Filename", "File name", "文件名")
k("Feature_Cluster", "Project cluster", "文件簇")
k("Feature_PersonalArtifact", "Personal", "个人属性")
k("Feature_ModificationPattern", "Modification pattern", "修改模式")
k("Feature_Unusualness", "Unusualness", "异常度")
k("Feature_AiScore", "AI score", "AI 评分")
k("Feature_LocalScore", "Local score", "本地评分")
k("Feature_StoryPotential", "Story potential", "故事潜力")
k("Feature_Technical", "Technical", "技术价值")
k("Feature_Historical", "Historical", "历史价值")

# ---------------------------------------------------------------- report
k("Report_Title", "Computer Archaeology Report", "计算机考古报告")
k("Report_Overview", "Overview", "总览")
k("Report_MostInteresting", "Most Interesting Discoveries", "最有趣的发现")
k("Report_MostInteresting_Intro", "The highest scoring artifacts of this run.", "本次运行中得分最高的文件。")
k("Report_ForgottenProjects", "Forgotten Projects", "被遗忘的项目")
k("Report_ForgottenProjects_Intro", "Folders that look like work someone started and then walked away from.", "看起来是某人开始后又放下的东西。")
k("Report_OldDocuments", "Old Documents", "老文档")
k("Report_OldDocuments_Intro", "Documents that have been sitting on this machine for years.", "在这台电脑上躺了很多年的文档。")
k("Report_StrangeFiles", "Strange Files", "奇怪文件")
k("Report_StrangeFiles_Intro", "Odd names, odd extensions, odd structure.", "奇怪的名字、扩展名或结构。")
k("Report_HistoricalArtifacts", "Historical Artifacts", "历史遗迹")
k("Report_HistoricalArtifacts_Intro", "The oldest traces found in this run.", "本次运行中发现的最古老的痕迹。")
k("Report_ImportantFiles", "Potentially Important Files", "可能重要的文件")
k("Report_ImportantFiles_Intro", "Files that may matter to you personally, and should not be lost.", "对你个人可能有意义、不应丢失的文件。")
k("Report_Timeline", "Timeline", "时间线")
k("Report_AiObservations", "AI Observations", "AI 观察")
k("Report_FinalSummary", "Final Summary", "总结")
k("Report_NoReport", "No report yet.", "还没有报告。")
k("Report_NoReportHint", "Complete an archaeology run to generate a report.", "完成一次考古后即可生成报告。")
k("Report_GeneratedAt", "Generated {0}", "生成于 {0}")
k("Report_Discovery", "Discovery #{0}", "发现 #{0}")
k("Report_WhyInteresting", "Why it is interesting", "为什么它有趣")
k("Report_Overview_Indexed",
  "Your computer's index contains {0} files.",
  "你的电脑索引中有 {0} 个文件。")
k("Report_Overview_Indexed_Unknown",
  "The file index could not be measured for this run.",
  "本次运行无法获知文件索引总量。")
k("Report_Overview_Examined_Ai",
  "This run examined {0} candidates. After local analysis and AI-assisted semantic analysis, {1} files were identified as particularly interesting.",
  "本次运行检查了 {0} 个候选文件，经过本地分析与 AI 语义分析后，识别出 {1} 个特别有趣的条目。")
k("Report_Overview_Examined_Local",
  "This run examined {0} candidates using local analysis only; {1} files were identified as particularly interesting.",
  "本次运行仅使用本地分析检查了 {0} 个候选文件，识别出 {1} 个特别有趣的条目。")
# Kept for reports archived by an earlier build so old sessions still render.
k("Report_Overview_Body",
  "Your computer's index contains {0} files. This run examined {1} candidates. After local analysis and AI-assisted semantic analysis, {2} files were identified as particularly interesting.",
  "你的电脑索引中有 {0} 个文件。本次运行检查了 {1} 个候选文件，经过本地分析与 AI 语义分析后，识别出 {2} 个特别有趣的条目。")
k("Report_Overview_BodyNoAi",
  "Your computer's index contains {0} files. This run examined {1} candidates using local analysis only; {2} files were identified as particularly interesting.",
  "你的电脑索引中有 {0} 个文件。本次运行仅使用本地分析检查了 {1} 个候选文件，识别出 {2} 个特别有趣的条目。")
k("Report_Observations_Empty", "Nothing crossed the interestingness threshold in this run.", "本次运行没有文件超过有趣值阈值。")
k("Report_Observations_Local", "The oldest artifact is {0}. The dominant categories are {1}.", "最古老的条目是 {0}。主要类别为 {1}。")
k("Report_FinalSummary_Local",
  "This run surfaced {0} artifacts. Nothing was modified, moved or deleted: Computer Archaeologist only reads.",
  "本次运行发现 {0} 个条目。程序没有修改、移动或删除任何文件：计算机考古学家只读取。")
k("Report_Fact_Indexed", "Indexed files", "索引文件数")
k("Report_Fact_Discovered", "Files discovered", "发现文件数")
k("Report_Fact_Candidates", "Candidates scored", "候选评分")
k("Report_Fact_AiAnalyzed", "AI analysed", "AI 分析数")
k("Report_Fact_Discoveries", "Discoveries", "发现数")
k("Report_Fact_Duration", "Duration", "耗时")
k("Report_Fact_Source", "Discovery engine", "发现引擎")
k("Report_Fact_Narrative", "Narrative", "叙述来源")
k("Report_Narrative_Ai", "Written by the configured AI model", "由配置的 AI 模型撰写")
k("Report_Narrative_Local", "Generated locally", "本地生成")
k("Report_AiUnavailable", "AI analysis was unavailable for some artifacts.", "部分文件没有可用的 AI 分析。")
k("Report_AiPartial", "AI analysis failed for some artifacts; local scoring was used for them.", "部分文件的 AI 分析失败，已使用本地评分。")
k("Report_AiSkipped", "AI analysis was skipped for this run.", "本次运行跳过了 AI 分析。")
k("Report_AiNotConfigured", "No OpenAI-compatible API is configured, so this report is local only.", "未配置 OpenAI 兼容 API，因此本报告仅基于本地分析。")
k("Report_CancelledPartial", "This run was cancelled; the report covers what was completed.", "本次运行被取消，报告仅覆盖已完成的部分。")
k("Report_Export", "Export as Markdown", "导出为 Markdown")
k("Report_Exported", "Report exported to {0}", "报告已导出到 {0}")
k("Report_ExportFailed", "The report could not be exported.", "报告导出失败。")
k("Report_Timeline_Year", "{0}", "{0}")
k("Report_Timeline_Count", "{0} artifact(s)", "{0} 个条目")
k("Report_OpenDetails", "View details", "查看详情")

# ---------------------------------------------------------------- settings
k("Settings_Title", "Settings", "设置")
k("Settings_Subtitle", "Everything here is stored locally. Your API key never touches a plain-text file.", "所有设置都保存在本地，API Key 不会以明文写入任何文件。")
k("Settings_OpenAi", "OpenAI-compatible API", "OpenAI 兼容 API")
k("Settings_OpenAi_Desc", "Any endpoint that speaks the OpenAI chat completions API works.", "任何兼容 OpenAI Chat Completions 的接口都可以使用。")
k("Settings_ApiKey", "API key", "API Key")
k("Settings_ApiKey_Placeholder", "sk-…", "sk-…")
k("Settings_ApiKey_Stored", "A key is currently stored. Enter a new one to replace it.", "已保存密钥。输入新值即可替换。")
k("Settings_ApiKey_Empty", "No API key stored.", "尚未保存 API Key。")
k("Settings_BaseUrl", "Base URL", "Base URL")
k("Settings_Model", "Model", "模型")
k("Settings_TestConnection", "Test connection", "测试连接")
k("Settings_Testing", "Testing…", "正在测试…")
k("Settings_ClearKey", "Clear API key", "清除 API Key")
k("Settings_Connected", "Connected", "连接成功")
k("Settings_KeySaved", "The API key is stored in the Windows Credential Manager.", "API Key 已存入 Windows 凭据管理器。")
k("Settings_KeyCleared", "The stored API key was cleared.", "已清除保存的 API Key。")
k("Settings_KeyStorage_CredentialManager", "Windows Credential Manager", "Windows 凭据管理器")
k("Settings_KeyStorage_Memory", "In-memory only", "仅内存")
k("Settings_Everything", "Everything", "Everything")
k("Settings_Everything_Desc", "Everything provides the file index used for discovery.", "Everything 提供用于发现文件的索引。")
k("Settings_EverythingStatus", "Status", "状态")
k("Settings_EverythingPath", "Everything SDK path", "Everything SDK 路径")
k("Settings_EverythingPath_Placeholder", "Leave empty to auto-detect Everything64.dll", "留空则自动查找 Everything64.dll")
k("Settings_EverythingCheck", "Check again", "重新检测")
k("Settings_EverythingDownload", "Download official SDK", "下载官方 SDK")
k("Settings_EverythingDownloading", "Downloading…", "正在下载…")
k("Settings_EverythingVersion", "Version", "版本")
k("Settings_Archaeology", "Archaeology", "考古")
k("Settings_MaxScan", "Maximum scanned files", "最大扫描文件数")
k("Settings_MaxCandidates", "Candidates kept after local scoring", "本地评分保留的候选数")
k("Settings_MaxAi", "Maximum AI analyses per run", "每次运行最大 AI 分析数")
k("Settings_MaxDiscoveries", "Maximum discoveries in the report", "报告中最大发现数")
k("Settings_MinScore", "Minimum interestingness", "最低有趣值")
k("Settings_Privacy", "Privacy", "隐私")
k("Settings_Privacy_Notice",
  "AI analysis may send selected file metadata or content excerpts to the configured OpenAI-compatible API. File discovery and scoring always happen locally.",
  "AI 分析可能会将选中文件的部分元数据或内容摘要发送到配置的 OpenAI 兼容 API。文件发现与评分始终在本地完成。")
k("Settings_Privacy_Metadata", "Metadata only", "仅元数据")
k("Settings_Privacy_Metadata_Desc", "Send names, paths, timestamps, size, extension and folder context. No file contents.", "发送文件名、路径、时间、大小、扩展名与文件夹上下文，不发送文件内容。")
k("Settings_Privacy_Smart", "Smart content", "智能内容")
k("Settings_Privacy_Smart_Desc", "Additionally read a small bounded excerpt from text-like files when it helps.", "在有助于判断时，额外读取文本类文件的少量内容。")
k("Settings_Privacy_Off", "Disable AI content analysis", "禁止 AI 内容分析")
k("Settings_Privacy_Off_Desc", "No request is ever sent. Everything runs locally and the report is generated locally.", "完全不发送任何请求，全部本地运行并生成报告。")
k("Settings_AnalyzeImages", "Analyse image metadata", "分析图片元数据")
k("Settings_AnalyzeImages_Desc", "Read dimensions and format from image headers. Pixels are never uploaded.", "从图片文件头读取尺寸与格式，绝不上传图像像素。")
k("Settings_AnalyzeCode", "Analyse code structure", "分析代码结构")
k("Settings_AnalyzeArchives", "Analyse archive listings", "分析压缩包列表")
k("Settings_MaxContentBytes", "Maximum content excerpt (bytes)", "内容摘要最大字节数")
k("Settings_ExcludedPaths", "Excluded paths", "排除路径")
k("Settings_ExcludedPaths_Desc", "Additional folders to ignore. Built-in system, cache and build-output exclusions always apply.", "额外忽略的文件夹。系统目录、缓存与构建产物的内置排除始终生效。")
k("Settings_ExcludedExtensions", "Excluded extensions", "排除扩展名")
k("Settings_ExcludedExtensions_Desc", "Additional extensions to ignore, for example .iso", "额外忽略的扩展名，例如 .iso")
k("Settings_IncludedRoots", "Restrict discovery to", "限定搜索范围")
k("Settings_IncludedRoots_Desc", "When empty, the whole machine is explored.", "留空则搜索整台电脑。")
k("Settings_AddPlaceholder_Path", "D:\\Old Projects", "D:\\Old Projects")
k("Settings_AddPlaceholder_Extension", ".tmp", ".tmp")
k("Settings_Appearance", "Appearance", "外观")
k("Settings_Theme", "Theme", "主题")
k("Settings_Theme_Light", "Light", "浅色")
k("Settings_Theme_Dark", "Dark", "深色")
k("Settings_Theme_System", "Follow system", "跟随系统")
k("Settings_Language", "Language", "语言")
k("Settings_Language_System", "Follow system", "跟随系统")
k("Settings_Advanced", "Advanced", "高级")
k("Settings_Fallback", "Allow built-in fallback discovery", "允许内置回退扫描")
k("Settings_Fallback_Desc",
  "Only used when Everything is unavailable. It walks fixed drives with hard time and file limits, and is much slower.",
  "仅在 Everything 不可用时使用。它会遍历本地磁盘，并带有时间与文件数硬限制，速度慢得多。")
k("Settings_Concurrency", "Concurrent AI requests", "AI 并发请求数")
k("Settings_Timeout", "Request timeout (seconds)", "请求超时（秒）")
k("Settings_Retries", "Retries for 429 / 5xx / timeout", "429 / 5xx / 超时重试次数")
k("Settings_JsonMode", "Ask the endpoint for JSON output mode", "请求接口使用 JSON 输出模式")
k("Settings_HashTop", "Compute SHA-256 for final candidates", "为最终候选计算 SHA-256")
k("Settings_Weights", "Interestingness weights", "有趣值权重")
k("Settings_Weights_Desc", "Weights are normalised automatically, so they do not have to add up to 1.", "权重会自动归一化，无需合计为 1。")
k("Settings_Weight_Ai", "AI weight (scaled by confidence)", "AI 权重（按置信度缩放）")
k("Settings_Weight_MinConfidence", "Minimum confidence scale", "最低置信度系数")
k("Settings_ResetDefaults", "Reset to defaults", "恢复默认设置")
k("Settings_ResetConfirm_Title", "Reset all settings?", "恢复全部默认设置？")
k("Settings_ResetConfirm_Message", "Theme, language, API endpoint, archaeology limits and weights will all return to their defaults. The stored API key is not affected.", "主题、语言、API 地址、考古限制与权重都会恢复默认值。已保存的 API Key 不受影响。")
k("Settings_DataFolder", "Data folder", "数据目录")
k("Settings_OpenDataFolder", "Open data folder", "打开数据目录")
k("Settings_ThemeApplied", "Theme applied.", "主题已应用。")
k("Settings_LanguageApplied", "Language applied.", "语言已应用。")

# ---------------------------------------------------------------- everything status
k("Everything_Unknown", "Everything has not been checked yet.", "尚未检测 Everything。")
k("Everything_Available", "Everything is running and reachable.", "Everything 正在运行且可访问。")
k("Everything_NotInstalled", "Everything is not installed, or the SDK DLL was not found.", "未安装 Everything，或未找到 SDK DLL。")
k("Everything_NotRunning", "Everything is not running.", "Everything 未运行。")
k("Everything_IpcFailed", "Everything IPC failed.", "Everything IPC 通信失败。")
k("Everything_Incompatible", "The installed Everything version is not compatible with this SDK.", "已安装的 Everything 版本与 SDK 不兼容。")
k("Everything_Timeout", "The Everything query timed out.", "Everything 查询超时。")
k("Everything_PermissionDenied", "Access to Everything was denied.", "访问 Everything 被拒绝。")
k("Everything_QueryFailed", "The Everything query failed.", "Everything 查询失败。")
k("Everything_SdkNotWindows", "The Everything SDK is only available on Windows.", "Everything SDK 仅在 Windows 上可用。")
k("Everything_SdkDownloadFailed", "The official Everything SDK could not be downloaded.", "无法下载 Everything 官方 SDK。")
k("Everything_SdkInstalled", "The official Everything SDK was installed locally.", "Everything 官方 SDK 已安装到本地。")
k("Discovery_Source_Everything", "Everything index", "Everything 索引")
k("Discovery_Source_BuiltIn", "Built-in bounded scan", "内置受限扫描")
k("Discovery_FallbackReason", "Everything is unavailable, so the built-in enumerator was used.", "Everything 不可用，已使用内置枚举器。")
k("Discovery_FallbackInUse", "Everything is unavailable: the built-in bounded scan is in use.", "Everything 不可用：正在使用内置受限扫描。")

# ---------------------------------------------------------------- strategies
k("Strategy_Documents", "Documents", "文档")
k("Strategy_Notes", "Notes and text", "笔记与文本")
k("Strategy_SourceCode", "Source code", "源代码")
k("Strategy_Projects", "Project files", "项目文件")
k("Strategy_GameSaves", "Game saves", "游戏存档")
k("Strategy_Archives", "Archives", "压缩包")
k("Strategy_Images", "Images", "图片")
k("Strategy_Media", "Audio and video", "音视频")
k("Strategy_Design", "Design and 3D", "设计与 3D")
k("Strategy_Configs", "Configuration", "配置文件")
k("Strategy_Databases", "Databases", "数据库")
k("Strategy_Spreadsheets", "Spreadsheets", "表格")
k("Strategy_Presentations", "Presentations", "演示文稿")
k("Strategy_KeywordNames", "Suggestive file names", "带暗示的文件名")
k("Strategy_YearNames", "Years in file names", "文件名中的年份")
k("Strategy_Letters", "Mail and contacts", "邮件与联系人")
k("Strategy_Logs", "Logs and history", "日志与历史")
k("Strategy_ForgottenByDate", "Not modified for years", "多年未修改")
k("Strategy_AncientByCreation", "Created long ago", "很久以前创建")

# ---------------------------------------------------------------- categories
k("Category_forgotten_project", "Forgotten Project", "被遗忘的项目")
k("Category_old_document", "Old Document", "老文档")
k("Category_old_photo", "Old Photo", "老照片")
k("Category_game_save", "Game Save", "游戏存档")
k("Category_source_code", "Source Code", "源代码")
k("Category_strange_file", "Strange File", "奇怪文件")
k("Category_configuration", "Configuration", "配置文件")
k("Category_log_file", "Log File", "日志文件")
k("Category_archive", "Archive", "压缩包")
k("Category_personal_note", "Personal Note", "个人笔记")
k("Category_school_work", "School Work", "学生作业")
k("Category_media", "Media", "媒体")
k("Category_unknown", "Unclassified", "未分类")

# ---------------------------------------------------------------- score reasons
k("Reason_Age_Years", "{0} years old (from {1})", "约 {0} 年历史（{1} 年）")
k("Reason_Age_None", "Too recent for age to matter.", "时间太新，年龄不构成价值。")
k("Reason_Age_Recent", "Modified within the last year.", "一年内修改过。")
k("Reason_Rarity_Rare", "The {0} extension appears only {1} time(s) in {2} scanned files.", "在已扫描的 {2} 个文件中，{0} 扩展名仅出现 {1} 次。")
k("Reason_Rarity_Common", "The {0} extension is very common ({1} occurrences).", "{0} 是非常常见的扩展名（{1} 次出现）。")
k("Reason_Rarity_None", "The extension is not especially rare.", "扩展名并不特别稀有。")
k("Reason_Path_Personal", "Located in a folder that looks personal or dated ({0}).", "位于看起来属于个人或有年代感的目录（{0}）。")
k("Reason_Path_Transient", "Located in a temporary, cached or system folder.", "位于临时、缓存或系统目录中。")
k("Reason_PathContext_None", "The folder says nothing in particular.", "所在目录没有特别的语义。")
k("Reason_Filename_Keyword", "The file name carries the signal(s): {0}.", "文件名包含线索：{0}。")
k("Reason_Filename_None", "The file name is unremarkable.", "文件名很普通。")
k("Reason_Cluster_Project", "The folder holds {0} files ({1} of them source) and looks like a project.", "该文件夹包含 {0} 个文件（其中 {1} 个是源代码），看起来像一个项目。")
k("Reason_Cluster_Siblings", "The folder holds {0} related files.", "该文件夹包含 {0} 个相关文件。")
k("Reason_Cluster_Alone", "The file sits alone in its folder.", "该文件在目录中单独存在。")
k("Reason_Personal_Type", "{0} files are usually made by a person rather than by the system.", "{0} 文件通常由人创建，而不是系统生成。")
k("Reason_PersonalArtifact_None", "Not an obviously personal file type.", "不是明显的个人文件类型。")
k("Reason_Mod_Abandoned", "Created {0}, last modified {1}, then left alone.", "创建于 {0}，最后修改于 {1}，之后一直被搁置。")
k("Reason_Mod_Active", "Still being modified ({0}).", "仍在被修改（{0}）。")
k("Reason_Mod_Steady", "Last modified {0}.", "最后修改于 {0}。")
k("Reason_ModificationPattern_None", "The modification history is unremarkable.", "修改历史没有特别之处。")
k("Reason_Unusual_Flags", "Unusual characteristics: {0}.", "异常特征：{0}。")
k("Reason_Unusual_None", "Nothing structurally unusual.", "结构上没有异常。")
k("Reason_LocalOnly", "Scored from local measurements only.", "仅根据本地测量评分。")

# ---------------------------------------------------------------- AI
k("Ai_Connected", "Connected", "连接成功")
k("Ai_TestFailed", "The connection test failed.", "连接测试失败。")
k("Ai_RequestFailed", "AI request failed", "AI 请求失败")
k("Ai_Error_NoKey", "No API key is configured.", "尚未配置 API Key。")
k("Ai_Error_InvalidEndpoint", "The base URL is not a valid absolute URL.", "Base URL 不是有效的绝对地址。")
k("Ai_Error_BadRequest", "The endpoint rejected the request (400).", "接口拒绝了该请求（400）。")
k("Ai_Error_Unauthorized", "The API key was rejected (401).", "API Key 被拒绝（401）。")
k("Ai_Error_Forbidden", "Access to this model or endpoint is forbidden (403).", "无权访问该模型或接口（403）。")
k("Ai_Error_NotFound", "The endpoint or model was not found (404).", "未找到该接口或模型（404）。")
k("Ai_Error_RateLimited", "The API rate limit was hit (429). The request was retried automatically.", "触发了 API 速率限制（429），已自动重试。")
k("Ai_Error_Server", "The API returned a server error.", "接口返回服务器错误。")
k("Ai_Error_Timeout", "The request timed out.", "请求超时。")
k("Ai_Error_Network", "A network error occurred.", "网络错误。")
k("Ai_Error_InvalidJson", "The model did not return valid JSON, even after a repair attempt.", "模型未返回有效 JSON，修复尝试也失败。")
k("Ai_Error_EmptyResponse", "The model returned an empty response.", "模型返回了空响应。")
k("Ai_Error_ModelUnavailable", "The configured model is unavailable.", "配置的模型不可用。")
k("Ai_Error_AllRequestsFailed", "Every AI request failed during this run.", "本次运行中所有 AI 请求都失败了。")

# ---------------------------------------------------------------- warnings + errors
k("Warning_ScanLimitReached", "The configured maximum number of files was reached; the scan stopped early.", "已达到配置的最大文件数，扫描提前结束。")
k("Warning_Cancelled", "The run was cancelled; partial results were kept.", "运行已取消，部分结果已保留。")
k("Warning_CancelledDuringAi", "Cancellation happened during AI analysis; some candidates were not analysed.", "在 AI 分析阶段取消，部分候选未被分析。")
k("Warning_SettingsLoadFailed", "The settings file could not be read and defaults were used.", "设置文件读取失败，已使用默认值。")
k("Error_Title", "Something went wrong", "出现问题")
k("Error_Unexpected", "An unexpected error occurred.", "发生了意外错误。")
k("Error_Settings", "The settings could not be saved.", "设置保存失败。")
k("Error_ScanFailed", "The archaeology run failed.", "考古运行失败。")
k("Error_EverythingIpc", "Communication with Everything failed.", "与 Everything 通信失败。")


# ---------------------------------------------------------------- late additions
k("Home_HistoryRow", "{0} files · {1} discoveries", "{0} 个文件 · {1} 个发现")
k("Detail_ConfidenceValue", "Confidence {0}%", "置信度 {0}%")
k("Settings_KeyStorageFormat", "Stored in: {0}", "保存位置：{0}")

def write_resw(path, table, lang):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n')
        f.write('<root>\n')
        f.write('  <resheader name="resmimetype">\n    <value>text/microsoft-resx</value>\n  </resheader>\n')
        f.write('  <resheader name="version">\n    <value>2.0</value>\n  </resheader>\n')
        f.write('  <resheader name="reader">\n    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>\n  </resheader>\n')
        f.write('  <resheader name="writer">\n    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>\n  </resheader>\n')
        for key in sorted(table):
            value = table[key]
            value = value.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            f.write(f'  <data name="{key}" xml:space="preserve">\n    <value>{value}</value>\n  </data>\n')
        f.write('</root>\n')

def main():
    base = sys.argv[1]
    write_resw(os.path.join(base, "en-US", "Resources.resw"), EN, "en-US")
    write_resw(os.path.join(base, "zh-CN", "Resources.resw"), ZH, "zh-CN")

    missing = set(EN) ^ set(ZH)
    if missing:
        print("KEY MISMATCH:", sorted(missing))
        sys.exit(1)
    print(f"Wrote {len(EN)} keys per language to {base}")

if __name__ == "__main__":
    main()
